package com.tenxengage.app.batch.seed;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Guards the coupling between {@code V3__baseline_tenant_and_config.sql}'s seeded
 * partner companies and the {@code %.example.com} filter used by
 * {@link SeedDataRunner#loadExistingPartners} and
 * {@code SeedCleanupService#cleanupAllData}. Both sites treat a Contact Email ending in
 * {@code .example.com} as "auto-generated by the seed batch" and therefore filter it
 * out when merging Flyway-seeded partners or preserving baseline partners during
 * cleanup. If a hand-seeded partner's email happens to end in {@code .example.com},
 * it silently collides with the filter and that partner is excluded from every seed
 * stage keyed off {@code enrolledPartnerSet} — reproducing BUG-003.
 */
class BaselineSeedPartnerFilterIntegrityTest {

    private static final Path V3_MIGRATION = Paths.get(
        "src/main/resources/db/migration/V3__baseline_tenant_and_config.sql");

    private static final Pattern PARTNER_COMPANIES_INSERT = Pattern.compile(
        "INSERT INTO partner_companies VALUES \\(.*?\\);", Pattern.DOTALL);

    private static final Pattern CONTACT_EMAIL = Pattern.compile(
        "\"Contact Email\"\\s*:\\s*\"([^\"]+)\"");

    @Test
    void baselinePartnerCompanies_contactEmailDoesNotCollideWithSeedFilter() throws IOException {
        String sql = Files.readString(V3_MIGRATION, StandardCharsets.UTF_8);

        Matcher inserts = PARTNER_COMPANIES_INSERT.matcher(sql);
        int partnersChecked = 0;
        while (inserts.find()) {
            String stmt = inserts.group();
            Matcher emailMatch = CONTACT_EMAIL.matcher(stmt);
            assertThat(emailMatch.find())
                .as("Every V3 partner_companies INSERT must carry a Contact Email so the seed "
                    + "filter can decide whether to merge it. Statement: %s", stmt)
                .isTrue();

            String email = emailMatch.group(1);
            assertThat(email)
                .as("Baseline partner Contact Email %s ends in '.example.com' and collides with "
                    + "the SeedDataRunner/SeedCleanupService filter — this partner would be "
                    + "excluded from enrolledPartnerSet and see zero POs/claims/rewards "
                    + "(BUG-003). Use a real domain (e.g. techpartners.com) for hand-seeded "
                    + "partners and reserve '.example.com' for auto-generated ones.", email)
                .doesNotEndWith(".example.com");
            partnersChecked++;
        }

        assertThat(partnersChecked)
            .as("V3 migration must seed at least one partner_companies row; 0 found means the "
                + "regex broke or the baseline seed was deleted.")
            .isGreaterThanOrEqualTo(1);
    }
}
